Refactoring trait pipeline (2/2)
talmolab/sleap-roots pull request #48
Opened 2023-07-28 02:55 UTC by eberrigan

2023-07-28 04:04 UTC, talmo requested changes

2023-07-28 04:04 UTC, talmo commented on sleap_roots/bases.py
> +        bottom lateral root base.
Should be 1 line

2023-07-28 04:04 UTC, talmo commented on sleap_roots/bases.py
> +        or base_ys (instances).
indent

2023-08-01 19:16 UTC, eberrigan commented on sleap_roots/bases.py
> +    Return maximum root length for all roots in a frame.
Done

2023-08-01 19:17 UTC, eberrigan commented on sleap_roots/bases.py
> +        OR
Done

2023-08-01 19:17 UTC, eberrigan commented on sleap_roots/bases.py
> +        OR
Done

2023-08-01 19:19 UTC, eberrigan commented on sleap_roots/bases.py
> +    Get x coordinates of the base of each lateral root.
Done

2023-08-02 17:52 UTC, merged